apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/mac/kompose -f ../docker-compose/docker-compose-park-and-ride-deploy.yml -f ../docker-compose/docker-compose-park-and-ride.yml -f ../docker-compose/docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: parking-updater
  name: parking-updater
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: parking-updater
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mac/kompose -f ../docker-compose/docker-compose-park-and-ride-deploy.yml -f ../docker-compose/docker-compose-park-and-ride.yml -f ../docker-compose/docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: parking-updater
    spec:
      containers:
        - command:
            - sh
            - -c
            - node index.js
          env:
            - name: INPUTS_PATH
              value: /opt/inputs
          envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE, ROOT_PATH
            - configMapRef:
                name: reacsimenv-configmap
          image: macfltechdev.azurecr.io/updater:2024-3q
          name: parking-updater
          resources:
            limits:
              memory: "134217728"
          volumeMounts:
            - mountPath: /opt/inputs
              name: parking-updater-inputs
      restartPolicy: Always
      volumes:
        - name: parking-updater-inputs
          persistentVolumeClaim:
            claimName: reacsim-inputs
            readOnly: true
      initContainers:
        - name: wait-for-prepare
          image: bitnami/kubectl:1.24
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -exc
            - kubectl wait --for condition=complete job/prepare
