apiVersion: v1
kind: Pod
metadata:
  name: parking-updater
spec:
  containers:
    - command:
        - sh
        - -c
        - node index.js
      env:
        - name: INPUTS_PATH
          value: /opt/inputs
      envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE, ROOT_PATH
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/updater:2024-3q
      name: parking-updater
      resources:
        limits:
          memory: "134217728"
      volumeMounts:
        - mountPath: /opt/inputs
          name: parking-updater-inputs
  restartPolicy: Never
  volumes:
    - name: parking-updater-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
        readOnly: true
  initContainers:
    - name: wait-for-prepare
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=complete job/prepare --timeout 1h
