# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: exec-kubectl

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-kubectl
rules:
  - apiGroups: ["", "apps", "batch", "kafka.strimzi.io"]
    resources: ["services", "endpoints", "pods", "deployments", "jobs", "kafkas"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-kubectl
subjects:
  - kind: ServiceAccount
    # name: exec-kubectl
    name: default
roleRef:
  kind: Role
  name: exec-kubectl
  apiGroup: ""
