apiVersion: v1
kind: Pod
metadata:
  name: toll-calculator
spec:
  containers:
    - env:
        - name: CLASSPATH
          value: /opt/jars/domain-simulator/calculator/toll-calculator/toll-calculator-1.0.0-jar-with-dependencies.jar
        - name: INPUTS_PATH
          value: /opt/inputs
        - name: REACSIM_SIMULATOR_NAME
          value: toll-calculator
      envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/javaruntime:2024-3q
      name: toll-calculator
      resources:
        limits:
          memory: "268435456"
      volumeMounts:
        - mountPath: /opt/inputs
          name: toll-calculator-inputs
        - mountPath: /opt/jars
          name: toll-calculator-jars
  restartPolicy: Never
  volumes:
    - name: toll-calculator-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
        readOnly: true
    - name: toll-calculator-jars
      persistentVolumeClaim:
        claimName: reacsim-jars
        readOnly: true
  initContainers:
    - name: wait-for-kafka
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready kafka/my-cluster --timeout 1h
    - name: wait-for-prepare
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=complete job/prepare --timeout 1h
