apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/mac/kompose -f ./docker-compose/docker-compose.yml -f docker-compose/docker-compose-initial-location.yml -f docker-compose/docker-compose-initial-location-deploy.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: sumo-v2
  name: sumo-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: sumo-v2
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mac/kompose -f ./docker-compose/docker-compose.yml -f docker-compose/docker-compose-initial-location.yml -f docker-compose/docker-compose-initial-location-deploy.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: sumo-v2
    spec:
      containers:
        - env:
            - name: INPUTS_PATH
              value: /opt/inputs
            - name: LOGGING_LEVEL
              value: INFO
            - name: REACSIM_SIMULATOR_NAME
              value: sumo-v2
            - name: SUMO_NET_FILE
              value: /opt/inputs/map.net.xml.gz
          envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE
            - configMapRef:
                name: reacsimenv-configmap
          image: macfltechdev.azurecr.io/sumo-v2.1:2024-3q
          livenessProbe:
            exec:
              command:
                - ss
                - ( dport = :9092 )
            failureThreshold: 5
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          name: sumo-v2
          resources:
            limits:
              memory: "2147483648"
          volumeMounts:
            - mountPath: /opt/inputs
              name: sumo-v2-inputs
      restartPolicy: Always
      volumes:
        - name: sumo-v2-inputs
          persistentVolumeClaim:
            claimName: reacsim-inputs
            readOnly: true
      initContainers:
        - name: wait-for-kafka
          image: bitnami/kubectl:1.24
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -exc
            - kubectl wait --for condition=ready kafka/my-cluster
