apiVersion: v1
kind: Pod
metadata:
  name: end
spec:
  containers:
    - env:
        - name: SERVER
          value: http://mac-work-fltechdev.japaneast.cloudapp.azure.com:40203
      envFrom: # SIMULATION_ID
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/end:2024-3q
      name: end
      volumeMounts:
        - mountPath: /opt/outputs
          name: end-outputs
        - mountPath: /opt/inputs
          name: end-inputs
          readOnly: true
  restartPolicy: Never
  volumes:
    - name: end-outputs
      persistentVolumeClaim:
        claimName: reacsim-simulations
    - name: end-inputs
      persistentVolumeClaim:
        claimName: reacsim-outputs
        readOnly: true
  initContainers:
    - name: wait-for-dumperjs-ready
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        # - while :; do ready=$(kubectl get job/dumperjs -o json | jq .status.ready); if [ ${ready} -eq 1 ]; then break; fi; sleep 1; done
        - kubectl wait --for condition=ready=true pod/dumperjs --timeout 1h
    - name: wait-for-dumperjs
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready=false pod/dumperjs --timeout 1h
