apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kompose.cmd: /home/mac/kompose -f ./docker-compose/docker-compose.yml -f docker-compose/docker-compose-initial-location.yml -f docker-compose/docker-compose-initial-location-deploy.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: prepare
  name: prepare
spec:
  # replicas: 1
  # selector:
  #   matchLabels:
  #     io.kompose.service: prepare
  # strategy:
  #   type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mac/kompose -f ./docker-compose/docker-compose.yml -f docker-compose/docker-compose-initial-location.yml -f docker-compose/docker-compose-initial-location-deploy.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: prepare
    spec:
      containers:
        - env:
            - name: INPUTS_PATH
              value: /opt/inputs
          envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE, DMM_MODEL_INFO_FILE
            - configMapRef:
                name: reacsimenv-configmap
          image: macfltechdev.azurecr.io/prepare:2024-3q
          name: prepare
          volumeMounts:
            - mountPath: /opt/inputs
              name: prepare-inputs
          # command: ["sleep", "infinity"]
      restartPolicy: Never
      volumes:
        - name: prepare-inputs
          persistentVolumeClaim:
            claimName: reacsim-inputs
      initContainers:
        - name: wait-for-start
          image: bitnami/kubectl:1.24
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -exc
            - kubectl wait --for condition=complete job/start --timeout 1h

