apiVersion: v1
kind: Pod
metadata:
  name: sdt-dmm-service
  labels:
    service: sdt-dmm-service
spec:
  containers:
    - envFrom: # DMM_MODEL_INFO_FILE
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/sdt-dmm-service:2024-3q
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:8140/ping
        failureThreshold: 5
        initialDelaySeconds: 60
        periodSeconds: 30
        timeoutSeconds: 30
      name: sdt-dmm-service
      resources:
        limits:
          memory: "536870912"
      volumeMounts:
        - mountPath: /opt/inputs
          name: sdt-dmm-service-inputs
  restartPolicy: Never
  volumes:
    - name: sdt-dmm-service-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
  initContainers:
    - name: wait-for-prepare
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=complete job/prepare --timeout 1h

