apiVersion: v1
kind: Pod
metadata:
  name: otp
spec:
  containers:
    - env:
        - name: INPUTS_PATH
          value: /opt/inputs
        - name: LOGGING_LEVEL
          value: INFO
        - name: REACSIM_SIMULATOR_NAME
          value: otp
      envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/otp:2024-3q
      name: otp
      resources:
        limits:
          memory: "268435456"
      volumeMounts:
        - mountPath: /opt/inputs
          name: otp-inputs
  restartPolicy: Never
  volumes:
    - name: otp-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
        readOnly: true
  initContainers:
    - name: wait-for-kafka
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready kafka/my-cluster --timeout 1h
    - name: wait-for-opentripplanner
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/opentripplanner --timeout 1h
    - name: wait-for-prepare
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=complete job/prepare --timeout 1h
