apiVersion: apps/v1
kind: Deployment
metadata:
  name: reacsim-data
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: reacsim-data
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: reacsim-data
    spec:
      containers:
        - name: reacsim-data
          image: alpine:latest          
          args:
            - /bin/sh
            - -c
            - sleep infinity
          resources:
            limits:
              memory: "536870912"
          volumeMounts:
            - mountPath: /opt/inputs
              name: reacsim-inputs
            - mountPath: /opt/outputs
              name: reacsim-outputs
            - mountPath: /opt/jars
              name: reacsim-jars
            - mountPath: /opt/simulations
              name: reacsim-simulations
      restartPolicy: Always
      volumes:
        - name: reacsim-inputs
          persistentVolumeClaim:
            claimName: reacsim-inputs
        - name: reacsim-outputs
          persistentVolumeClaim:
            claimName: reacsim-outputs
        - name: reacsim-jars
          persistentVolumeClaim:
            claimName: reacsim-jars
        - name: reacsim-simulations
          persistentVolumeClaim:
            claimName: reacsim-simulations
