apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: reacsim-outputs
  name: reacsim-outputs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
