apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: reacsim-simulations
  name: reacsim-simulations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
