apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reacsim-simulations
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: reacsim-simulations-pv
  storageClassName: azureblob-fuse-premium