apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reacsim-jars
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: reacsim-jars-pv
  storageClassName: azureblob-fuse-premium