apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/mac/kompose -f ../docker-compose/docker-compose-park-and-ride-deploy.yml -f ../docker-compose/docker-compose-park-and-ride.yml -f ../docker-compose/docker-compose.yml convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: opentripplanner
  name: opentripplanner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: opentripplanner
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /home/mac/kompose -f ../docker-compose/docker-compose-park-and-ride-deploy.yml -f ../docker-compose/docker-compose-park-and-ride.yml -f ../docker-compose/docker-compose.yml convert
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: opentripplanner
    spec:
      containers:
        - args:
            - --build
            - --serve
            - --port
            - "8080"
          envFrom: # JAVA_OPTS, JAVA_TOOL_OPTIONS, CONFIG_DIR
            - configMapRef:
                name: opentripplanner-configmap
          # image: docker.io/opentripplanner/opentripplanner:2.5.0
          image: macfltechdev.azurecr.io/reacsimopentripplanner:2.5.0
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/otp/actuators/health
            failureThreshold: 5
            initialDelaySeconds: 600
            periodSeconds: 30
            timeoutSeconds: 30
          name: opentripplanner
          resources:
            limits:
              memory: "6442450944"
          volumeMounts:
            - mountPath: /opt/inputs
              name: opentripplanner-inputs
      restartPolicy: Always
      volumes:
        - name: opentripplanner-inputs
          persistentVolumeClaim:
            claimName: reacsim-inputs
            readOnly: true
