apiVersion: v1
kind: Pod
metadata:
  labels:
    service: opentripplanner
  name: opentripplanner
spec:
  containers:
    - args:
        - --build
        - --serve
        - --port
        - "8080"
      envFrom: # JAVA_OPTS, JAVA_TOOL_OPTIONS, CONFIG_DIR
        - configMapRef:
            name: opentripplanner-configmap
      # image: docker.io/opentripplanner/opentripplanner:2.5.0
      image: macfltechdev.azurecr.io/reacsimopentripplanner:2.5.0
      livenessProbe:
        exec:
          command:
            - curl
            - -f
            - http://localhost:8080/otp/actuators/health
        failureThreshold: 5
        initialDelaySeconds: 600
        periodSeconds: 30
        timeoutSeconds: 30
      name: opentripplanner
      resources:
        limits:
          memory: "6442450944"
      volumeMounts:
        - mountPath: /opt/inputs
          name: opentripplanner-inputs
  restartPolicy: Never
  volumes:
    - name: opentripplanner-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
  initContainers:
    - name: wait-for-prepare
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=complete job/prepare --timeout 1h
