apiVersion: v1
kind: Pod
metadata:
  name: assimil
spec:
  containers:
    - args:
        - java
        - -DLOGGING_LEVEL=INFO
        - com.fujitsu.assimil.Assimil
      env:
        - name: CLASSPATH
          value: /opt/jars/assimil/assimil-1.0.2-jar-with-dependencies.jar:/opt/jars/usecases/initial-location/assimil/initial-location-1.0.0.jar:/opt/jars/usecases/dynamic-discount/assimil/dynamic-discount-1.0.0.jar:/opt/jars/usecases/park-and-ride/assimil/park-and-ride-1.0.0.jar
        - name: INPUTS_PATH
          value: /opt/inputs
      envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/javaruntime:2024-3q
      name: assimil
      resources:
        limits:
          memory: "2684354560"
      volumeMounts:
        - mountPath: /opt/inputs
          name: assimil-inputs
        - mountPath: /opt/jars
          name: assimil-jars
  restartPolicy: Never
  volumes:
    - name: assimil-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
        readOnly: true
    - name: assimil-jars
      persistentVolumeClaim:
        claimName: reacsim-jars
        readOnly: true
  initContainers:
    - name: wait-for-flow-provider
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/flow-provider --timeout 1h
    - name: wait-for-parking
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/parking --timeout 1h
    - name: wait-for-traffic-simple
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/traffic-simple --timeout 1h
