apiVersion: v1
kind: Pod
metadata:
  name: flow-provider
spec:
  containers:
    - env:
        - name: CLASSPATH
          value: /opt/jars/domain-simulator/flow/flow-provider/flow-provider-1.0.3-jar-with-dependencies.jar
        - name: INPUTS_PATH
          value: /opt/inputs
        - name: REACSIM_SIMULATOR_NAME
          value: flow-provider
      envFrom: # SIMULATION_ID, REACSIM_CONFIG_FILE
        - configMapRef:
            name: reacsimenv-configmap
      image: macfltechdev.azurecr.io/javaruntime:2024-3q
      name: flow-provider
      resources:
        limits:
          memory: "268435456"
      volumeMounts:
        - mountPath: /opt/inputs
          name: flow-provider-inputs
        - mountPath: /opt/jars
          name: flow-provider-jars
  restartPolicy: Never
  volumes:
    - name: flow-provider-inputs
      persistentVolumeClaim:
        claimName: reacsim-inputs
        readOnly: true
    - name: flow-provider-jars
      persistentVolumeClaim:
        claimName: reacsim-jars
        readOnly: true
  initContainers:
    - name: wait-for-kafka
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready kafka/my-cluster --timeout 1h
    - name: wait-for-dumperjs
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/dumperjs --timeout 1h
    - name: wait-for-action-selector
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/action-selector --timeout 1h
    - name: wait-for-vehicle-planner
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/vehicle-planner --timeout 1h
    - name: wait-for-dmm
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/dmm --timeout 1h
    - name: wait-for-otp
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/otp --timeout 1h
    - name: wait-for-sumo-v2
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/sumo-v2 --timeout 1h
    - name: wait-for-station
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/station --timeout 1h
    - name: wait-for-fee-calculator
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/fee-calculator --timeout 1h
    - name: wait-for-fuelcost-calculator
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/fuelcost-calculator --timeout 1h
    - name: wait-for-parkcharge-calculator
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/parkcharge-calculator --timeout 1h
    - name: wait-for-lowbattery-discount
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/lowbattery-discount --timeout 1h
    - name: wait-for-return-discount
      image: bitnami/kubectl:1.24
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -exc
        - kubectl wait --for condition=ready pods/return-discount --timeout 1h
