apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- name: reacsimenv-configmap
  envs:
  - reacsim.env

bases:
- ../base
- ../fee-calculator
- ../fuelcost-calculator
- ../parkcharge-calculator
- ../station
- ../sumo-v2
- ../vehicle-planner
- ../lowbattery-discount
- ../return-discount

resources:
- flow-provider-deployment.yaml
- assimil-deployment.yaml
