seed: ${RANDOM_SEED}

# Kafka topics
kafka:
  topics:
    assimil: assimil
    simulators:
      sumo-v2: sumo
      station: station
      dmm: dmm
      flow-provider: flow-provider
      action-selector: action-selector
      vehicle-planner: vehicle-planner
      fee-calculator: fee-calculator
      fuelcost-calculator: fuelcost-calculator
      parkcharge-calculator: parkcharge-calculator
    metrics:
      states: metrics-pos
      output: metrics-travel
      current-usage: metrics-escooter-usage
      total-usage: metrics-escooter-total
      choice: metrics-choice
  producer:
    bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS}
    linger.ms: 1
  consumer:
    bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS}
    auto.offset.reset: earliest

assimil:
  # Number of object stages (same as stage of dracena)
  numberOfStages: 2

  # Aligner settings
  aligner:
    classPath: com.fujitsu.assimil.aligner.SimpleAligner
    stepLength: 10

    # Number of simulation run steps (seconds)
    maxSteps: ${ASSIMIL_ALIGNER_MAX_STEPS}

    # start time of simulation (hour)
    startTime: ${ASSIMIL_ALIGNER_START_TIME}

  # Initial object settings
  objects:
    # Person object (use CSV)
    - classPath: com.fujitsu.assimil.example.Person
      csv: ${INPUTS_PATH}/${ASSIMIL_PERSON_FILE}
      parameters:
        flowProvider: flow-provider

    # Station object (use CSV)
    - classPath: com.fujitsu.measures.Station
      csv: ${INPUTS_PATH}/${SOARS_STATIONS_FILE}
      oidKey: name
      parameters:
        type: escooter
        simulator: station
        lowBatteryPercent: 15
        currentMetrics: current-usage
        totalMetrics: total-usage

  # metrics settings
  metrics:
    states:
      classPath: com.fujitsu.assimil.metrics.ThrottleDump
      throttle: 60
    output:
      classPath: com.fujitsu.assimil.metrics.Pass
      ignoreEmpty: true
    current-usage:
      classPath: com.fujitsu.assimil.metrics.ThrottleDump
      throttle: 60
    total-usage:
      classPath: com.fujitsu.assimil.metrics.Pass
      ignoreEmpty: true

  # annotation settings (false to speed up)
  annotation:
    metrics: false
    state: false

# Settings for each simulator
simulators:
  sumo-v2:
    sumocfg: ${INPUTS_PATH}/configs/sumo/reacsim.sumocfg
    net: ${INPUTS_PATH}/${SUMO_NET_FILE}
    gui: false
    stepLength: 10 # Simulation step interval (seconds)
    findRouteDistance: 50 # allowable distance (m)

  dmm:
    modelInfoFile: ${DMM_MODEL_INFO_FILE}
    serverHost: sdt-dmm-service
    serverPort: 8140
    accessToken: 1234567asdfgh
    currencyRate: ${CURRENCY_RATE}

  flow-provider:
    vTypes: ${VTYPES}
    detour:
    planners: car,vehicle-planner,pedestrian,vehicle-planner,escooter,vehicle-planner
    simulators: car,sumo-v2,pedestrian,sumo-v2,escooter,sumo-v2,station,station

  vehicle-planner:
    assimilStep: 10
    fee: escooter,fee-calculator
    fuelCost: car,fuelcost-calculator
    toll:
    parkCharge: car,parkcharge-calculator
    feeMeasures:
    planNumber: 4 # shared mobility max plan number

  fee-calculator:
    currencyRate: ${CURRENCY_RATE}

  fuelcost-calculator:
    currencyRate: ${CURRENCY_RATE}

  parkcharge-calculator:
    currencyRate: ${CURRENCY_RATE}
